### ISSUE TITLE
how to modify https://raw.github.com/laas/ros/master/laas.rosinstall

### ISSUE THREAD

**Issue by MaximilienNaveau** [stack-of-tasks/install-sot#26]
Good evening everyone,

I check things on internet but I couldn't find any explanation on how the laas.rosinstall could have been uploaded.
You can download it easily with a :
wget  https://raw.github.com/laas/ros/master/laas.rosinstall  --output-document=/tmp/laas.rosinstall

but I need to do an update on this files.
If you have an answer I would be glad to here it.

Thanks, and have a good week end.

**Comment by francois-keith** [comment]
Hello

This file comes from this repository: https://github.com/laas/ros
This link is what you get when you select a file through the github interface and click on "raw" (in your case for the branch master).
